In [2]:
import numpy as np

### Numpy Basics

In [3]:
array_1 = np.array([1,5,656])

In [4]:
array_1

array([  1,   5, 656])

In [5]:
array_1.shape

(3,)

In [35]:
arr2 = np.array([[1,2,3], [4,5,6]], dtype = 'int8')

In [36]:
arr2

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

In [37]:
arr2.ndim

2

In [38]:
arr2.shape

(2, 3)

In [39]:
arr2.dtype

dtype('int8')

In [40]:
arr2[0, 1] = 100

In [41]:
arr2

array([[  1, 100,   3],
       [  4,   5,   6]], dtype=int8)

In [42]:
arr2[0, 1]

100

### Changng Specific raws, clolumns, specific elements 

In [47]:
arr2[:, 1:-1:1]

array([[100],
       [  5]], dtype=int8)

In [48]:
arr2[:,2] = [5]

In [49]:
arr2

array([[  1, 100,   5],
       [  4,   5,   5]], dtype=int8)

### 3D numpy arrays 

In [73]:
arr3 = np.array([[[1, 2, 3, 10], [4, 5, 6, 11], [7, 8, 9, 12]]])

In [74]:
arr3

array([[[ 1,  2,  3, 10],
        [ 4,  5,  6, 11],
        [ 7,  8,  9, 12]]])

In [75]:
arr3.dtype

dtype('int32')

In [76]:
type(arr3)

numpy.ndarray

In [77]:
arr3.ndim

3

In [78]:
arr3.shape

(1, 3, 4)

In [79]:
arr3

array([[[ 1,  2,  3, 10],
        [ 4,  5,  6, 11],
        [ 7,  8,  9, 12]]])

In [80]:
arr3[0, 0]

array([ 1,  2,  3, 10])

In [81]:
arr3

array([[[ 1,  2,  3, 10],
        [ 4,  5,  6, 11],
        [ 7,  8,  9, 12]]])

### Get specific elements (inside out)

In [86]:
arr3[0,0,3]

10

In [87]:
arr3[0][1]

array([ 4,  5,  6, 11])

## Initailising Different types of arrays

In [109]:
arr4 = np.zeros((3, 4), dtype = 'int32')

In [110]:
arr4

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [113]:
arr5 = np.ones((4,5), dtype = 'int32')

In [114]:
arr5

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [118]:
arr6 = np.full((3,2,8), 9)

In [120]:
arr6

array([[[9, 9, 9, 9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9, 9, 9, 9]],

       [[9, 9, 9, 9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9, 9, 9, 9]],

       [[9, 9, 9, 9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9, 9, 9, 9]]])

In [122]:
arr7 = np.full_like(arr6, 5)

In [123]:
arr7

array([[[5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5]]])

In [131]:
arr8 = np.random.randint(4, 7, size = (4, 4))

In [132]:
arr8

array([[4, 5, 5, 6],
       [6, 6, 5, 6],
       [4, 6, 5, 6],
       [6, 4, 6, 5]])

In [134]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### problem statememnt

In [135]:
output = np.ones((5, 5))

In [136]:
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [137]:
inside = np.zeros((3, 3))
print(inside)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [138]:
inside[1, 1] = 9
print(inside)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [143]:
output[1:-1, 1:-1] = inside
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### be careful while copying arrays 

In [151]:
a = np.array([10,34,45])

In [152]:
b = np.copy(a)

In [154]:
b[0] = 9999

In [155]:
print(a)
print(b)

[10 34 45]
[9999   34   45]


## Mathematics 

In [174]:
a = np.array([1,2,3,4,5,6])

In [175]:
a += 2
print(a)

[3 4 5 6 7 8]


In [176]:
a - 1

array([2, 3, 4, 5, 6, 7])

In [177]:
a * 2

array([ 6,  8, 10, 12, 14, 16])

In [178]:
a * 2

array([ 6,  8, 10, 12, 14, 16])

In [179]:
a

array([3, 4, 5, 6, 7, 8])

In [181]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ,
        0.98935825])

### Linear algebra

In [183]:
a = np.ones((4,5))
print(a)

b = np.full((5, 4), 3)
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [188]:
c = np.matmul(a, b)
print(c)

[[15. 15. 15. 15.]
 [15. 15. 15. 15.]
 [15. 15. 15. 15.]
 [15. 15. 15. 15.]]


In [190]:
d = np.linalg.det(c)
print(d)

0.0


### Statistics

In [191]:
a = np.array([[[1, 2, 3, 10], [4, 5, 6, 11], [7, 8, 9, 12]]])

In [205]:
np.max(a)

12

In [206]:
np.min(a)

1

In [207]:
np.sum(a)

78

### Rearranging Arrays

In [208]:
a = np.array([[[1, 2, 3, 10], [4, 5, 6, 11], [7, 8, 9, 12]]])

In [210]:
a.shape

(1, 3, 4)

In [215]:
a = a.reshape((4, 3))

In [216]:
a.shape

(4, 3)

### Stacks -- vertical and horizontal 

In [217]:
s1 = np.array([1, 2, 3, 4])
s2 = np.array([6, 7, 8, 9])

In [220]:
p = np.vstack([s1, s2, s2, s1])

In [221]:
p

array([[1, 2, 3, 4],
       [6, 7, 8, 9],
       [6, 7, 8, 9],
       [1, 2, 3, 4]])

In [222]:
p = np.hstack([s1, s2, s2, s1])

In [223]:
p

array([1, 2, 3, 4, 6, 7, 8, 9, 6, 7, 8, 9, 1, 2, 3, 4])

### Krishna Naik

In [234]:
q = np.random.randint(4, size = (4, 4))

In [235]:
q

array([[3, 1, 2, 1],
       [2, 0, 0, 2],
       [3, 0, 1, 0],
       [1, 3, 0, 2]])

In [250]:
a = np.arange(0, stop = 10, step = 1)

In [249]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [271]:
b = np.linspace(2, 10, 10, True)

In [272]:
c = b.reshape(5, 2)

In [273]:
c

array([[ 2.        ,  2.88888889],
       [ 3.77777778,  4.66666667],
       [ 5.55555556,  6.44444444],
       [ 7.33333333,  8.22222222],
       [ 9.11111111, 10.        ]])

In [274]:
c.shape

(5, 2)